services:
  radicale:
    image: ghcr.io/kozea/radicale:stable
    container_name: radicale
    restart: unless-stopped
    networks:
      - traefik-proxy
    volumes:
      - /opt/homelab/radicale/config:/etc/radicale
      - /opt/homelab/radicale/data:/var/lib/radicale
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.radicale.rule=Host(`calendar.gionet.eu`)"
      - "traefik.http.routers.radicale.entrypoints=https"
      - "traefik.http.routers.radicale.tls.certresolver=letsencrypt"
      - "traefik.http.services.radicale.loadbalancer.server.port=5232"

networks:
  traefik-proxy:
    external: true
